### ISSUE TITLE
User Datasets: port client code from wdkclient to this repo

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-user-datasets#1]

**Comment by jtlong3rd** [comment]
Resolved by #4. As a followup, I will also need to excise the old client code from WDKClient.

**Comment by danicahelb** [comment]
@jtlong3rd how should the outreach team QA this?

**Comment by jtlong3rd** [comment]
> @jtlong3rd how should the outreach team QA this?

No testing is required! This work was purely internal - I just migrated legacy client code from [one repository](https://github.com/VEuPathDB/WDKClient) to this one.

**Comment by danicahelb** [comment]
thanks, moving to "completed"
