### ISSUE TITLE
DIY: Error message for "recent upload" when upload dataset

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/web-user-datasets#18]
When upload dataset, it pops out error message: " Could not retrieve upload history" (see the pic). It also happens sometimes when the dataset has been uploaded successfully. In order to see whether it is loaded successfully, need to click "All" to see whether uploaded dataset is showed.  
<img width="2227" alt="Screen Shot 2022-07-11 at 11 03 07 AM" src="https://user-images.githubusercontent.com/61077845/178309768-288bcc18-3151-4c51-a8f8-dc5ebb16b784.png">

**Comment by jtlong3rd** [comment]
Resolved by https://github.com/VEuPathDB/service-user-dataset-import/pull/32. Thanks @dmgaldi!

**Comment by SheenaTomko** [comment]
This message no longer appears
