### ISSUE TITLE
User Datasets: upload form page

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-user-datasets#2]
Where is the form configuration defined?

- [ ] Select ud type (rnaseq, genelist, user study)
- [x] Show form with fields for this type
- [x] Show upload options for this type (url, files)

**Comment by ryanrdoherty** [comment]
@jtlong3rd We previously discussed the model for which user dataset types will be displayed in the select box, but not sure if you were part of that meeting.  The design is this:

1. user dataset upload service will add a metadata endpoint that has a list of available type plugins (i.e. handlers), probably with an ID, title/displayName, and (maybe) description
2. WDK sites will declare (maybe in ebrc project service override?) a list of user dataset type IDs that particular site wants to support (e.g. clinepi sites won't show rna_seq type)
3. Client code will show the drop down at the top with options representing the intersection of the udus-supported types and those desired by the specific site.
4. User selects the type, then a site-specific form is displayed (most types probably using a default form)

**Comment by danicahelb** [comment]
FYI I'm moving this ticket to b59. We want DIY to be publicly released in b59, but made available on the QA site in b58.

**Comment by jtlong3rd** [comment]
Closing this issue, as all that was needed for "Phase 1" of the new User Datasets UI was the `Show form with fields for this type` and `Show upload options for this type (url, files)` subtasks. I will open a new separate issue for `Select ud type (rnaseq, genelist, user study)`.

**Comment by jtlong3rd** [comment]
I created an issue for `Select ud type (rnaseq, genelist, user study)` [here](https://github.com/VEuPathDB/web-user-datasets/issues/22)

**Comment by SheenaTomko** [comment]
Looks good
