### ISSUE TITLE
VDI User datasets: Update icons used to indicate status

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-user-datasets#26]
We need to evaluate whether/how to change the icons used on the user dataset page. 

This screenshot shows the error message you get if trying to start an upload without all the required fields. May want to pick a new warning icon
<img width="416" alt="Screen Shot 2022-07-13 at 4 36 53 PM" src="https://user-images.githubusercontent.com/54597319/178830048-2f57f0bf-661c-45c8-ab15-65fe0d164e67.png">

This screenshot shows the 3 different types of status messages and icons you can see on the Recent uploads tab. Consider changing the gear to a clock to indicate in progress?
<img width="629" alt="Screen Shot 2022-07-13 at 4 37 19 PM" src="https://user-images.githubusercontent.com/54597319/178830191-1da09f98-4db1-4fe0-be6b-a50508dd2ac4.png">

This screenshot shows 2 of the status symbols on the All tab. The check is green, the clock is blue. Should we make that yellow to indicate in progress? I will upload another screenshot when this upload fails to show what the grey fail icon looks like 
<img width="1024" alt="Screen Shot 2022-07-13 at 4 37 37 PM" src="https://user-images.githubusercontent.com/54597319/178830332-c2a51d72-b997-42a3-85ba-5adb618fd0af.png">

**Comment by jernestmyers** [comment]
Discussed in styling WG meeting on [December 7th, 2022](https://veupathdb.atlassian.net/l/cp/1KrRF1X3). Mock ups and decisions are included in the agenda and/or linked to in the agenda.

**Comment by danicahelb** [comment]
Figma icons here: https://www.figma.com/file/31Sop27q3WgfxL0iv8g3RN/user-datasets-status?node-id=0-1&t=W9FG0fu0g8a7CxQV-0

**Comment by aurreco-uga** [comment]
this has changed considearbly in vdi so we should review
